export { default as AcademicReportFiltersModal } from './AcademicReportFiltersModal'
export { default as AcademicStudentsTable } from './AcademicStudentsTable'
export { default as AcademicReportGenerationModal } from './AcademicReportGenerationModal'
export { default as AcademicStatisticsCards } from './AcademicStatisticsCards'
export { default as AcademicStudentDetailsModal } from './AcademicStudentDetailsModal'
