export { default as AcademicReportFilters } from './AcademicReportFilters'
export { default as AcademicStudentsTable } from './AcademicStudentsTable'
export { default as AcademicReportGenerationModal } from './AcademicReportGenerationModal'
export { default as AcademicStatisticsCards } from './AcademicStatisticsCards'
export { default as AcademicStudentDetailsModal } from './AcademicStudentDetailsModal'
